# EXERCÍCIOS COM NUMPY
**Essas são as resoluções de algumas questões de análise de dados com a biblioteca numpy**

In [1]:
#Importando a biblioteca:
import numpy as np

In [2]:
#Martiz de booleanos 4x3:
a = np.full((4,3), True, dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
#Martiz de booleanos 2x2:
b = np.full((2,2), False, dtype=bool)
print(b)

[[False False]
 [False False]]


In [5]:
#Extraindo todos os números ímpares do array c:
c = np.array([0,1,2,3,4,5,6,7,8,9])
c[c % 2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
#Extraindo todos os números pares do array d:
d = np.array([0,1,2,3,4,5,6,7,8,9])
d[d % 2 == 0]

array([0, 2, 4, 6, 8])

In [7]:
#Substituindo todos os números ímpares do array e por -1
e = np.array([0,1,2,3,4,5,6,7,8,9])
e[e % 2 == 1] = -1
e

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#Substituindo todos os números pares do array f por 2
f = np.array([0,1,2,3,4,5,6,7,8,9])
f[arr % 2 == 1] = -1
f